
name: Aria2Ng

services:
    aria2-ng:
        image: sffzh/aria2-ng:1.37.0.1
        volumes:
            - /volume1/docker/aria2/config:/conf:rw
            - /volume1/Download:/data:rw
        ports:
            - "8080"
            - "6800/tcp/udp"
        restart: unless-stopped
        environment:
            - SECRET=go_eidt_/volume1/docker/aria2/config/aria2.conf
