name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    steps:
    - run: echo “${DOCKER_PASSWORD}” | docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      name: Login Docker Hub
    - uses: actions/checkout@v4
      name: Build the Docker image
    - run: fullCommit="${{ github.event.commits[0].id }}" && \
           docker build . --file Dockerfile --tag sffzh/Docker-Aria2NG:$ARIA2_VERSION --tag sffzh/Docker-Aria2NG:${ARIA2_VERSION}-"${fullCommit:0:7}"  &&\
           docker push sffzh/Docker-Aria2NG:$ARIA2_VERSION
